# 通信服务配置
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

# 数据库配置
data:
  # 关系型数据库, 当前只支持mysql
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  # redis缓存
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

# 运行环境配置
env:
  name: "prometheus-manager-master"
  version: "v0.0.1"
  namespace: "prometheus-manager"
  metadata:
    env: "dev"
    description: "Kratos Layout App"

# 链路追踪 jaeger
trace:
  endpoint: http://127.0.0.1:14268/api/traces

# 服务注册和发现 ETCD
registrar:
  etcd:
    endpoints:
      - localhost:20000
      - localhost:20002
      - localhost:20004

# 推送策略配置
push_strategy:
  # 推送策略的频率
  interval: 10s
  # 默认的推送策略到node的文件目录, 此目录必须在node的配置文件中(strategy.path)配置
  dir: /tmp/prometheus-manager
  # 是否开启推送策略
  enable: false
  # 手动注册到master的节点
  nodes:
    - server_name: "prometheus-manager-node"
      timeout: 1s
      network: "grpc" # grpc, http, https

# 告警配置, 目前采用kafka
kafka:
  # 接收告警信息的topic
  alert_topic: "prometheus-manager-node-alert"
  # 是否开启告警监听
  enable: false
  # kafka的地址
  endpoints:
    - "localhost:9092"
