version: '3'

services:
  prometheus_manager:
    container_name: prometheus_manager
    image: docker.hub/prometheus-manager/app/prom_server:latest
    ports:
      - "8001:8000"
      - "9001:9000"
    volumes:
      - "./app/prom_server/configs_dev/:/data/conf/"
      - "./app/prom_server/cache:/app/cache"

  prometheus_manager_agent:
    container_name: prometheus_manager_agent
    image: docker.hub/prometheus-manager/app/prom_agent:latest
    ports:
      - "8002:8000"
      - "9002:9000"
    volumes:
      - "./app/prom_agent/configs_dev/:/data/conf/"
      - "./app/prom_agent/cache:/app/cache"
    depends_on:
      - prometheus_manager

  prometheus_manager_web:
    container_name: prometheus_manager_web
    image: docker.hub/prometheus-manager/web:latest
    ports:
      - "8000:80"
    depends_on:
      - prometheus_manager