data:
  main:
    driver: ${X_MOON_DATA_MAIN_DRIVER:MYSQL}
    debug: ${X_MOON_DATA_MAIN_DEBUG:true}
    useSystemLog: ${X_MOON_DATA_MAIN_USE_SYSTEM_LOG:false}
    user: ${X_MOON_DATA_MAIN_USER:root}
    password: ${X_MOON_DATA_MAIN_PASSWORD:123456}
    host: ${X_MOON_DATA_MAIN_HOST:127.0.0.1}
    port: ${X_MOON_DATA_MAIN_PORT:3306}
    params: ${X_MOON_DATA_MAIN_PARAMS:charset=utf8mb4&parseTime=True&loc=Local}
    dbName: ${X_MOON_DATA_MAIN_DB_NAME:moon_palace_main}

cache:
  driver: ${X_MOON_CACHE_DRIVER:MEMORY}
  network: ${X_MOON_CACHE_NETWORK:tcp}
  addr: ${X_MOON_CACHE_ADDR:127.0.0.1:6379}
  password: ${X_MOON_CACHE_PASSWORD}
  db: ${X_MOON_CACHE_DB:0}
  readTimeout: ${X_MOON_CACHE_READ_TIMEOUT:5s}
  writeTimeout: ${X_MOON_CACHE_WRITE_TIMEOUT:5s}
  dialTimeout: ${X_MOON_CACHE_DIAL_TIMEOUT:5s}
  clientName: ${X_MOON_CACHE_CLIENT_NAME}
  protocol: ${X_MOON_CACHE_PROTOCOL:0}
  username: ${X_MOON_CACHE_USERNAME}
  maxRetries: ${X_MOON_CACHE_MAX_RETRIES:0}
  minRetryBackoff: ${X_MOON_CACHE_MIN_RETRY_BACKOFF:0s}
  maxRetryBackoff: ${X_MOON_CACHE_MAX_RETRY_BACKOFF:0s}
  contextTimeoutEnabled: ${X_MOON_CACHE_CONTEXT_TIMEOUT_ENABLED:false}
  poolFifo: ${X_MOON_CACHE_POOL_FIFO:false}
  poolSize: ${X_MOON_CACHE_POOL_SIZE:0}
  poolTimeout: ${X_MOON_CACHE_POOL_TIMEOUT:0s}
  minIdleConns: ${X_MOON_CACHE_MIN_IDLE_CONNS:0}
  maxIdleConns: ${X_MOON_CACHE_MAX_IDLE_CONNS:0}
  maxActiveConns: ${X_MOON_CACHE_MAX_ACTIVE_CONNS:0}
  connMaxIdleTime: ${X_MOON_CACHE_CONN_MAX_IDLE_TIME:0s}
  connMaxLifetime: ${X_MOON_CACHE_CONN_MAX_LIFETIME:0s}
  disableIdentity: ${X_MOON_CACHE_DISABLE_IDENTITY:false}
  identitySuffix: ${X_MOON_CACHE_IDENTITY_SUFFIX}
  unstableResp3: ${X_MOON_CACHE_UNSTABLE_RESP3:false}
