aliyunSMSConfigs:
  - name: 'default'
    accessKeyId: ${X_MOON_RABBIT_ALIYUN_SMS_ACCESS_KEY_ID}
    accessKeySecret: ${X_MOON_RABBIT_ALIYUN_SMS_ACCESS_KEY_SECRET}
    signName: ${X_MOON_RABBIT_ALIYUN_SMS_SIGN_NAME}
    endpoint: ${X_MOON_RABBIT_ALIYUN_SMS_ENDPOINT}
