environment: ${X_MOON_HOUYI_ENVIRONMENT:DEV}

server:
  name: ${X_MOON_HOUYI_SERVER_NAME:houyi}
  metadata:
    summary: ${X_MOON_HOUYI_SUMMARY}
  teamIds: ${X_MOON_HOUYI_TEAM_IDS:[]}
  outEndpoint: ${X_MOON_HOUYI_OUT_ENDPOINT:localhost:9090}
  onlineInterval: ${X_MOON_HOUYI_ONLINE_INTERVAL:10s}
  network: ${X_MOON_HOUYI_NETWORK:GRPC}
  http:
    network: ${X_MOON_HOUYI_HTTP_NETWORK:tcp}
    addr: ${X_MOON_HOUYI_HTTP_ADDR:0.0.0.0:8080}
    timeout: ${X_MOON_HOUYI_HTTP_TIMEOUT:5s}
    allowHeaders: ${X_MOON_HOUYI_HTTP_ALLOW_HEADERS:['*']}
    allowMethods: ${X_MOON_HOUYI_HTTP_ALLOW_METHODS:['*']}
    allowOrigins: ${X_MOON_HOUYI_HTTP_ALLOW_ORIGINS:['*']}

  grpc:
    network: ${X_MOON_HOUYI_GRPC_NETWORK:tcp}
    addr: ${X_MOON_HOUYI_GRPC_ADDR:0.0.0.0:9090}
    timeout: ${X_MOON_HOUYI_GRPC_TIMEOUT:5s}

registry:
  driver: ${X_MOON_HOUYI_REGISTRY_DRIVER:ETCD}
  enable: ${X_MOON_HOUYI_REGISTRY_ENABLE:false}
  etcd:
    endpoints: ${X_MOON_HOUYI_REGISTRY_ETCD_ENDPOINTS:['127.0.0.1:2379']}
    timeout: ${X_MOON_HOUYI_REGISTRY_ETCD_TIMEOUT:5s}
    username: ${X_MOON_HOUYI_REGISTRY_ETCD_USERNAME}
    password: ${X_MOON_HOUYI_REGISTRY_ETCD_PASSWORD}

palace:
  endpoint: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_ENDPOINT:127.0.0.1:9000}
  secret: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_SECRET:moon-jwt-sign-key}
  timeout: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_TIMEOUT:5s}
  network: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_NETWORK:GRPC}
  version: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_VERSION:1.0.0}
  name: ${X_MOON_HOUYI_MICRO_SERVER_PALACE_NAME:palace}
