env:
  name: moon_prom_agent
  version: 0.0.1
  env: dev
  metadata:
    description: Prometheus Manager Agent APP
    version: 0.0.1
    author: 梧桐
    license: MIT
    email: aidecloud@163.com
    url: https://github.com/aide-family/moon

server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
#data:
#  # 配置redis， 缓存使用redis， 否则使用本地存储
#  redis:
#    addr: host.docker.internal:6379
#    read_timeout: 0.2s
#    write_timeout: 0.2s

log:
  filename: ./log/agent.log
  level: debug
  encoder: json
  maxSize: 500
  compress: true

watchProm:
  interval: 10s
  version: v2

# NOTE: 实际运行中需要替换为容器可访问地址，当前主机为容器在本地一站式拉起可访问的主机地址，生产根据自身配置修改
interflow:
  hook:
    http:
      agent:
#        url: http://host.docker.internal:8002/api/v1/interflows/receive
        url: http://localhost:8001/api/v1/interflows/receive
      server:
#        url: http://host.docker.internal:8001/api/v1/interflows/receive
        url: http://localhost:8000/api/v1/interflows/receive

#    grpc:
#      agent:
#        endpoints:
#          - host.docker.internal:9002
#      server:
#        endpoints:
#          - host.docker.internal:9001
#
#  mq:
#    kafka:
#      groupId: prometheus-agent
#      endpoints:
#        - host.docker.internal:9092